import {combatSource,bosses} from './data';

export type GuideSource={sourceTitle:string;sourceUrl:string;lastUpdated:string;kind:'Official / Pre-release'|'Community / Pre-release'|'Project documentation'};
export type Guide={slug:string;title:string;description:string;lastUpdated:string;limitation:string;sources:GuideSource[];sections:{id:string;title:string;paragraphs:string[]}[];related:{name:string;href:string}[]};
const updated='2026-09-09';
const revision='1947c51';
const project=(path:string,sourceTitle:string):GuideSource=>({sourceTitle,sourceUrl:`https://github.com/TANGCC101/phantom-blade-zero-tools/blob/${revision}/${path}`,lastUpdated:updated,kind:'Project documentation'});
const combat:GuideSource={...combatSource,kind:'Official / Pre-release'};
const policy=project('docs/decisions/2026-09-09-v1-completion.md','PBZ Tools — V1 implementation and editorial decisions');
const planner=project('src/components/BuildPlanner.tsx','PBZ Tools — planner interface and local-save behavior');
const tracker=project('src/components/Tracker.tsx','PBZ Tools — scheduled tracker transition and backups');

export const guides:Guide[]=[
 {
  slug:'combat-system-overview',title:'Phantom Blade Zero combat systems: a pre-release overview',
  description:'Understand the official weapon-system preview, separate announcements from unknowns, and turn combat ideas into useful planning notes.',
  lastUpdated:updated,
  limitation:'Pre-release overview, not a combat tutorial for the released game. Exact controls, damage, compatibility and encounter tactics are outside this guide.',
  sources:[combat,policy,planner],
  sections:[
   {id:'official-preview',title:'What the developer has described',paragraphs:['The August 17, 2026 S-GAME post on PlayStation Blog describes more than 30 main weapons and 25 secondary weapons, called Phantom Edges. It discusses accessories, weapon upgrades and reforging that returns materials for reuse. These are preview statements, not a verified launch catalog.']},
   {id:'read-the-overviews',title:'Read the system pages before making a list',paragraphs:['The weapon index on this site contains two system overviews. Opening Main weapons explains the scope of that category; opening Phantom Edges explains the secondary family. Neither page represents a single item you can equip. Use them to orient your research, then follow the source before recording a specific claim.','A count of announced weapons does not tell you their names, acquisition order or compatibility. Leave those questions open in your notes. A blank field with an explicit question is more useful than an invented answer that later looks authoritative.']},
   {id:'planning-workflow',title:'Turn a combat idea into a testable note',paragraphs:['In the planner, give an idea a descriptive name such as “First-session comparison.” Record the question you want to investigate in Strategy notes, together with its source URL and the date you read it. This is a suggested research workflow, not a recommended in-game build.','Keep three separate lines: what the source actually says, what you would like to try, and what remains unknown. When you can play, add your own observations with the game version and context. The planner stores your writing; it does not calculate damage or certify that a combination is possible.']},
   {id:'next-step',title:'Choose the next reference',paragraphs:['If the unfamiliar term is Phantom Edges, read the family guide next. If you want to preserve an idea, read the planner guide before saving or sharing it. For reported encounters, use the boss-reading guide so that an observation from a demo does not become a claim about the final game.']}
  ],related:[{name:'Weapon system overviews',href:'/weapons'},{name:'What are Phantom Edges?',href:'/guides/phantom-edges'},{name:'Using the build planner',href:'/guides/build-planner'},{name:'Open the planner',href:'/builds'}]
 },
 {
  slug:'phantom-edges',title:'What are Phantom Edges in Phantom Blade Zero?',
  description:'A sourced explanation of the secondary weapon family and how to record questions about it without inventing a final equipment catalog.',
  lastUpdated:updated,
  limitation:'The name describes a pre-release weapon family. This page does not provide a complete equipment list, unlock guide or verified slot layout.',sources:[combat,policy,planner],
  sections:[
   {id:'definition',title:'A family name, not one weapon',paragraphs:['S-GAME uses Phantom Edges for secondary weapons in its August 2026 preview. The post lists 25 and discusses ranged and summon-assisted combat options. It does not supply a complete item-by-item catalog.']},
   {id:'site-entry',title:'Why there is one Phantom Edges reference page',paragraphs:['Our weapons section groups available information at system level. Its Phantom Edges entry is a starting point for reading the developer source, not a selectable item with stats. Treating the entry as an individual weapon would confuse a category with the contents of that category.','The planner’s Secondary note is a free-text field. Writing a name there does not validate an item, equip it in the game or test it against the other fields. You can leave it blank while researching, or describe the question you intend to investigate.']},
   {id:'record',title:'A useful way to record an unresolved choice',paragraphs:['Create a planning note headed “Secondary option to investigate.” In Strategy notes, record the source title, link and reading date, followed by a question such as “Which option fits the way I want to play?” This example describes your research process; it makes no claim that a particular option exists.','When another source provides a specific name, preserve its context: developer announcement, press demo or your own play session. Do not silently replace an open question with a definite stat or unlock requirement. If the evidence changes, save a new copy with a clear name so you can distinguish the two ideas.']},
   {id:'unknowns',title:'Questions this reference leaves open',paragraphs:['Use the source to check whether a claim actually identifies an item, describes how it is acquired and applies to the same version you are playing. This site does not establish final damage, costs, cooldowns, upgrade paths or compatibility. A future item guide needs evidence for those details before they become database fields.']}
  ],related:[{name:'Phantom Edges system reference',href:'/weapons/phantom-edges'},{name:'Combat overview',href:'/guides/combat-system-overview'},{name:'Build planner',href:'/builds'},{name:'How reliability labels work',href:'/guides/data-reliability'}]
 },
 {
  slug:'build-planner',title:'How to use the Phantom Blade Zero build planner',
  description:'Save a combination locally, export and import JSON backups, and preview shared builds without overwriting your existing notes.',
  lastUpdated:updated,
  limitation:'Tool instructions checked against PBZ Tools V1. Pre-release note fields are not verified equipment slots, and the planner does not rank builds.',sources:[planner,project('src/lib/planner.ts','PBZ Tools — backup validation and share encoding'),policy],
  sections:[
   {id:'create',title:'1. Create and save a combination',paragraphs:['Open Build Planner and enter a Build name. Weapon note, Secondary note, Accessory note and Strategy notes are places for your own writing. Choose Save combination and look for the saved-on-device confirmation and a new card in Your builds.','Use as template loads an existing card into the form. Saving from that form creates a new copy; it does not edit the original card. Give the copy a recognizable name so you can tell an experiment from the earlier version.']},
   {id:'backup',title:'2. Back up before moving or clearing data',paragraphs:['Choose Download JSON backup to save the current collection. Keep the downloaded file somewhere you can find independently of this browser. Local saving is tied to this browser profile and site origin; another device, a private window or a future domain change will not automatically bring the collection across.','There is no account-based recovery. Before clearing site data, changing browsers or moving to another domain, export your collection. A shared link contains one build and is not a backup of the entire list.']},
   {id:'import',title:'3. Understand replacement when importing',paragraphs:['On the destination browser, open Import JSON and select a planner backup. The app validates the file, then asks whether to replace your saved list. Export any destination builds you want to keep before accepting. Import is replacement, not a merge.','The V1 importer accepts version 1 planner backups with unique IDs, up to 100 builds and a 1 MB input limit. A tracker backup is a different format. If validation fails, select the original planner export rather than manually guessing missing fields. If saving fails, the app reports the error and retains its current list.']},
   {id:'share',title:'4. Preview and save a shared build',paragraphs:['Choose Share on a saved card and copy the displayed link. It includes the build fields, including Strategy notes, in the URL fragment. Anyone who receives the full link can read those notes. Review the card before sharing and keep personal information out of it.','Opening a valid link shows a Shared preview. It does not overwrite saved builds. The recipient must choose Save a copy on this device to add it to their own collection. Later changes to either copy do not update the other: a share link is a snapshot, not a synchronized document.']}
  ],related:[{name:'Open Build Planner',href:'/builds'},{name:'Weapon references',href:'/weapons'},{name:'Sources and privacy',href:'/about'},{name:'Tracker backups',href:'/guides/progress-tracker'}]
 },
 {
  slug:'data-reliability',title:'How to read Phantom Blade Zero source and reliability labels',
  description:'Learn the difference between Official and Community sources, Pre-release and Verified stages, and editorial update dates on PBZ Tools.',
  lastUpdated:updated,
  limitation:'This is the independent site’s editorial policy. All current game reference entries remain Pre-release; this policy is not an endorsement by S-GAME.',sources:[policy,project('app/about/page.tsx','PBZ Tools — sourcing and privacy policy')],
  sections:[
   {id:'source',title:'First ask who published the information',paragraphs:['Official identifies developer or platform publications. Community covers independent press and player reports. These labels describe the source category, not a numerical confidence score. A detailed press observation can be useful while still being labeled Community.','Project documentation is a separate label on these guides. It supports statements about how this website saves, imports or displays your notes. It is not an official game source and should not be cited as proof of an in-game mechanic.']},
   {id:'stage',title:'Then ask which stage the evidence describes',paragraphs:['Pre-release means the information comes from announcements or demonstrations before release. Verified is reserved for facts checked against the released game. The two dimensions answer different questions: an Official source may still describe a Pre-release feature.','A calendar reaching the scheduled launch does not verify a reference entry. Neither a tracker checkbox nor your private planner note changes our editorial labels. Post-release checking must establish the relevant fact before an entry can be marked Verified.']},
   {id:'dates',title:'Read the source date and the editorial date separately',paragraphs:['The source may have been published well before our review. Last updated identifies the editorial date attached to this page or record; a source’s Checked date indicates when it was reviewed for the guide. Neither date means the developer released a new announcement that day.','For example, a demo article published in 2025 can be reviewed in September 2026 and still describe that earlier demo. Follow the linked source, check its original context, and avoid reading the newer review date as evidence of a newer game version.']},
   {id:'apply',title:'A short reading routine',paragraphs:['Read the claim, its source category and its stage together. Open the source and locate the passage supporting the claim. Then read the limitation: does the page describe a system, a single reported encounter or your own tool usage?','When sources disagree, retain their dates and contexts in your own research notes instead of combining them into one definitive statement. On this site, missing final stats and incomplete lists are intentional boundaries until evidence supports expanding them.']}
  ],related:[{name:'Editorial policy and privacy',href:'/about'},{name:'Weapon reference labels',href:'/weapons'},{name:'Reading boss reports',href:'/guides/boss-encounter-notes'},{name:'All guides',href:'/guides'}]
 },
 {
  slug:'boss-encounter-notes',title:'How to read Phantom Blade Zero boss encounter reports',
  description:'Understand the Seven Stars demo source, what the encounter entry does not establish, and how to keep your own observations separate.',
  lastUpdated:updated,
  limitation:'Selective Pre-release reporting, not a complete boss roster or a final-release walkthrough. No attack timings, rewards or mandatory progression are verified here.',
  sources:[{sourceTitle:'Sarah Thwaites / TechRadar — Phantom Blade Zero is a martial arts RPG packed with genre-twisting mythology',sourceUrl:bosses[0].sourceUrl,lastUpdated:updated,kind:'Community / Pre-release'},policy,tracker],
  sections:[
   {id:'seven-stars',title:'What the Seven Stars source actually reports',paragraphs:['In a hands-on article published September 8, 2025, TechRadar’s Sarah Thwaites describes a demo ending with a multi-stage encounter against the Chief Disciple of the Seven Stars. That first-hand demo report is the basis for this site’s selected encounter entry.','It establishes what the writer encountered in that demo. It does not establish the final game’s full boss order, the encounter’s mandatory status, exact attack windows or rewards. The page therefore carries Community and Pre-release labels.']},
   {id:'read-entry',title:'Read the encounter entry in three passes',paragraphs:['Start with the summary to identify the reported encounter. Read the notes to see what has deliberately been left unconfirmed. Finally, open the source and compare its publication date and demo context with the question you are trying to answer.','A named encounter in the index is not a complete guide to defeating it. Avoid treating a brief multi-stage description as a fixed number of final-release phases or a strategy that will work in every version. This site does not offer that level of evidence yet.']},
   {id:'own-notes',title:'Keep personal observations separate from reports',paragraphs:['When you can play, record the game version, difficulty, visible encounter name and what you actually observed. Keep an uncertain interpretation in a separate sentence. This is a suggested note-taking method, not a claim that the demo and your game will behave identically.','You can put those observations in the planner’s Strategy notes and use a descriptive build name to find them again. Preserve the link to the report alongside your notes so that someone reading a shared copy can distinguish the published observation from your own experience.']},
   {id:'checklist',title:'What a progress checkbox means',paragraphs:['After the scheduled transition, the tracker lets you mark the encounters in this site’s selected list. A checkmark is your personal completion record. It does not report completion to the game, prove that every boss is listed or upgrade the source entry to Verified.','Until there is a sourced, reviewed expansion of the index, treat the checklist as a small personal record. Use the tracker guide for backup instructions and the reliability guide for the conditions behind editorial labels.']}
  ],related:[{name:'Seven Stars encounter source',href:'/bosses/seven-stars'},{name:'Encounter index',href:'/bosses'},{name:'Progress tracker guide',href:'/guides/progress-tracker'},{name:'Reliability labels',href:'/guides/data-reliability'}]
 },
 {
  slug:'progress-tracker',title:'How to use the Phantom Blade Zero launch and progress tracker',
  description:'Prepare a local checklist, understand the scheduled launch transition, and back up personal boss progress without assuming a complete roster.',
  lastUpdated:updated,
  limitation:'The tracker uses a scheduled time, not live regional availability. Current encounter references remain Pre-release and the progress list is selective.',
  sources:[tracker,project('src/lib/tracker.ts','PBZ Tools — tracker state and import validation'),{sourceTitle:'PlayStation Store (US) — Phantom Blade Zero',sourceUrl:'https://store.playstation.com/en-us/concept/10017620',lastUpdated:updated,kind:'Official / Pre-release'}],
  sections:[
   {id:'before',title:'Before launch: record what you have reviewed',paragraphs:['Open the tracker and wait for the local clock to load. The pre-release checklist links to the release listing and combat announcement. Tick a box after reviewing its source. These boxes record your reading history; they do not unlock game content or register a purchase.','The countdown currently uses October 29, 2026 at 02:00 UTC, based on the US PlayStation Store listing checked September 9. Regional dates can differ. Follow your own platform’s listing when deciding when you can play.']},
   {id:'transition',title:'What changes at the scheduled time',paragraphs:['When the browser clock reaches the configured instant, the interface changes from Launch Countdown to Progress & Boss Tracker. It keeps the earlier checklist as Pre-release history and reveals the personal boss checklist. You do not need to discard the old record to start tracking.','This transition is controlled by time on your device. It does not contact the game or independently check store availability. If the display seems early or late, check your device clock and the linked official listing before interpreting it as a release announcement.']},
   {id:'progress',title:'After the transition: mark your own progress',paragraphs:['Use the Defeated checkbox beside an encounter to record your own completion. The Encounter notes link opens the source-backed entry. The current selection is not the full game roster, so completing every visible checkbox is not a claim that you have finished every boss.','Progress belongs to this browser and site origin. It is not connected to your game save, trophies or account. A personal check also does not change the editorial Pre-release status of the encounter.']},
   {id:'backup',title:'Back up the history and progress together',paragraphs:['Choose Download tracker JSON to export both the reviewed-announcement checklist and boss progress. Keep this file separate from planner backups: the two tools use different formats. Export before clearing site storage, switching devices or moving to another site domain.','On the destination browser, choose Import tracker JSON. A valid backup prompts you to replace current progress; export the destination state first if you need it. Invalid input leaves saved progress unchanged, and a storage failure is reported instead of silently claiming success. There is no cloud recovery of cleared local data.']}
  ],related:[{name:'Open the tracker',href:'/tracker'},{name:'Reading encounter reports',href:'/guides/boss-encounter-notes'},{name:'Planner backup guide',href:'/guides/build-planner'},{name:'Privacy and local storage',href:'/about'}]
 }
];
